### ISSUE TITLE
更新了最新的VS后，编译报错：未能找到类型或命名空间名“BindingImpl”(是否缺少using指令....) 

### ISSUE THREAD

**Issue by hcljq425** [jaceDeng/Alipay.Droid#1]
更新了最新的VS后，编译报错：未能找到类型或命名空间名“BindingImpl”(是否缺少using指令....)，
看了下好像是编译时放的obj文件报的错误，用老版本的VS就没问题。新版本的就会报这个错。

**Comment by jaceDeng** [comment]
我试试看

**Comment by jaceDeng** [comment]
Microsoft Visual Studio Enterprise 2017 
版本 15.7.2
VisualStudio.15.Release/15.7.2+27703.2018
Microsoft .NET Framework
版本 4.7.03062

已安装的版本: Enterprise
 我实验过了  没有问题的啊

**Comment by hcljq425** [comment]
额，是的，没问题，我自已没搞清楚。谢谢！
